### ISSUE TITLE
Chapter 4, Page 78

### ISSUE THREAD

**Issue by brianjgeiger** [editorscut/ec007-swift-kickstart#100]
The code sample doesn't match the screenshot. The screenshot has an item number in parentheses, but the code sample does not.

![screen shot 2014-10-25 at 6 01 29 pm](https://cloud.githubusercontent.com/assets/6599111/4781249/9d4a5c46-5c92-11e4-8cab-e66fafb338db.png)

**Comment by dimsumthinking** [comment]
Thanks Brian - 

This is fixed in Version 1.7 which ships soon!

Thanks,

Daniel
