### ISSUE TITLE
Book V1.6, Section 4.3, p76: Inconsistent feedback with Array.append

### ISSUE THREAD

**Issue by GaryDixon** [editorscut/ec007-swift-kickstart#101]
This section appears to have been verified against an earlier version of Swift.  The book says:

   “The feedback in the playground is a little inconsistent. When we use append() there is no feedback at all.”

The Swift in Xcode 6.1 now includes expected playground output when appending to an array.

coffeeDrinks.count                               // 1
coffeeDrinks                                         // ["Drip"]

coffeeDrinks.append("Decaf")             // ["Drip", "Decaf"]

**Comment by dimsumthinking** [comment]
Thank you - this is fixed in Version 1.7

Thanks,

Daniel
