### ISSUE TITLE
Book v1.6, Section 5.5, page 107: Invalid return in signature of func emphasize

### ISSUE THREAD

**Issue by GaryDixon** [editorscut/ec007-swift-kickstart#102]
The revised signature for func emphasize still shows returning an array.  The returned array was removed from this function several pages earlier.

“func emphasize(inout array: [String],
               modification: (String) -> String) -> [String] {
”

This should be:

func emphasize(inout array: [String],
                        modification: (String) -> String) {

**Comment by dimsumthinking** [comment]
Thank you,

This is now fixed in Version 1.7.

Thanks,

Daniel
