### ISSUE TITLE
Book v1.6, Section 6.10: Enumeration Subscripts, p 149

### ISSUE THREAD

**Issue by GaryDixon** [editorscut/ec007-swift-kickstart#103]
This section adds a subscript method to the enum BasketballPosition.  However, the return statement given in the book produces an error:

![screen shot 2014-12-14 at 2 59 47 pm](https://cloud.githubusercontent.com/assets/10003757/5429264/2a9d64fe-83a2-11e4-8f8c-3487c376dfc1.png)

The correct return statement does not include the dot:
               return BasketballPosition(rawValue: index)

**Comment by dimsumthinking** [comment]
My apologies for the typo - as you say, it's pretty significant.

Thanks for reporting this. I've fixed it in Version 1.7

Best,

Daniel
