### ISSUE TITLE
Book v1.6, Section 8.11, p 225, garbled sentence: If the count is zero of the index...

### ISSUE THREAD

**Issue by GaryDixon** [editorscut/ec007-swift-kickstart#104]
After code snippet that adds assert statements to the subscript get and set methods, the book attempts to explain actions implement by these asserts.  It says:

“If the count is zero of the index isn't smaller than the count then we will get a runtime exception. For example, create a new team with no players and ask for the player at index zero, like this.
”

Excerpt From: Daniel H Steinberg. “A Swift Kickstart.” Dim Sum Thinking, Inc, 2014. iBooks. https://itun.es/us/df9j1.l

I infer this sentence should be something like:
"If the count is zero, or if the index isn't smaller than the count, then we will get a runtime exception."

**Comment by dimsumthinking** [comment]
Thanks - it's a typo - the "f" in "of" was supposed to be an "r"

I've fixed it in version 1.7 - thank you for spotting it.

Best,

Daniel
