### ISSUE TITLE
Book v1.6, Section 4.7, Page 88 — Error in Playground Output

### ISSUE THREAD

**Issue by pnuesslein** [editorscut/ec007-swift-kickstart#106]
var numbers = [String:Int]()
numbers["one"] = 3
numbers["too"] = 4
numbers["one"] = 1                                              // {Some 1}
numbers.count                                                     // 2
numbers                                                              // ["two":4, "one":1]

At this point in the book you have not introduced the key "two", so the output should read 
// ["too":4, "one":1]

**Comment by dimsumthinking** [comment]
Thank you - this is fixed in Version 1.7 of the book.

Thanks,

Daniel
