### ISSUE TITLE
Chapter 3, page 48

### ISSUE THREAD

**Issue by scottdavis99** [editorscut/ec007-swift-kickstart#111]
Book Version: Version 1.8
Chapter: 3 Variables and Constants
Section: 2 Let
Page number: 48

The "What's the big deal" conversation bubble overlaps the previous code section

**Comment by dimsumthinking** [comment]
Sigh - I’’ve removed most of those conversation bubbles - might be time to just eliminate them - thank you!

Daniel

**Comment by dimsumthinking** [comment]
I've removed it. It makes me sad - but you are right.

Thank you,

Daniel
