### ISSUE TITLE
toPeopleNamed should be peopleNamed

### ISSUE THREAD

**Issue by wlmoss** [editorscut/ec007-swift-kickstart#115]
*A Swift Kickstart* version 1.8, Chapter 2, Section 7: "Variadic Parameters", Page 35

CONTEXT: "It has a single parameter with the external name **toPeopleNamed** and a local name people of type String...."

FIX: Change **toPeopleNamed** to just **peopleNamed**

EXPLANATION: The external parameter name used in the code examples throughout the section is inconsistent with the name used here in the text.

**Comment by dimsumthinking** [comment]
Fixed in version 1.9. Thank you for this.
