### ISSUE TITLE
Inconsistency in explanation of default variadic behavior

### ISSUE THREAD

**Issue by wlmoss** [editorscut/ec007-swift-kickstart#116]
*A Swift Kickstart* version 1.8, Chapter 2, Section 7: "Variadic Parameters", Page 36

CONTEXT: 

You can, however, easily provide default behavior 
by calling **sayHello()** from within **sayHello()** and providing 
a default value if people is empty, like this.
> func hello(peopleNamed people: String...) { 
>____if people.isEmpty {
>________print("Hello, World!")**

FIX:
1. In the text, change **sayHello()** to just **hello()**.
2. In the code, change **print("Hello, World!")** to **hello(peopleNamed: "World")**

EXPLANATION:
The first change is simply to be consistent with the name of the function used in the rest of the code and chapter.

The second change is to match the explanation of the self-referential call that the text says will occur.
While the if-condition will work without the self-referential call, it will be duplicating code unnecessarily (an unpleasant code "smell"). If the text no longer wants to espouse the self-referential call, then the text should be changed to better match what the code is doing.

**Comment by dimsumthinking** [comment]
Thank you - this is fixed in the version 1.9 update.
