### ISSUE TITLE
Stylistic reminder has inconsistent text in feedback

### ISSUE THREAD

**Issue by wlmoss** [editorscut/ec007-swift-kickstart#117]
"A Swift Kickstart" version 1.8, Chapter 2, Section 8: "Return Values", Page 38

CONTEXT:
Remember, I'll represent this feedback with a right justified comment like this.
.....
hello("my friend")______________________//  "Hello, World!"
.....

FIX:
Change **World** in the feedback comment to be **my friend**.

EXPLANATION:
The feedback output is just used as a reminder (and is not code to be entered)
but it is a distraction that the two do not match up. The easy fix is to simply make it consistent with the code used throughout the section.

**Comment by dimsumthinking** [comment]
Thank you -

This is fixed for version 1.9

Thanks
