### ISSUE TITLE
Unneeded instruction to inline print, v1.8, Ch 2, Sect 5, Pg 31

### ISSUE THREAD

**Issue by wlmoss** [editorscut/ec007-swift-kickstart#118]
Book Version: 1.8
Chapter: 2 Functions
Section: 5 Default Values
Page number: 31

CONTEXT:
Also, remove the no parameter `hello()` function. ~~This means we have to inline the print() call.~~
...
This lets us eliminate our hello() that takes a single parameter. **Again, we have to inline the print() call.**

FIX:
1. The body of the single parameter hello() function is unchanged from its state at the start of the chapter. The addition of the default string value is sufficient to replicate the action of the no-parameter function.
2. The style sheet for the function block should also be restyled from red "changed" to the blue "unchanged" code style.
3. At the bottom of the page in the second consolidation, it *is* necessary to inline the print() call, but this is the first time it must be done. Instead of simply eliminating the word "Again", you may want to explain what's going on "We have to inline the print() call because we are now eliminating the function hello() previously depended upon."

**Comment by dimsumthinking** [comment]
Thank you for this - it was such a thoughtful, well described change. I've made it and it will be part of Version 1.9.
