### ISSUE TITLE
v1.8, Ch 3, Sect 5, Pg 54, Second code block uses inconsistent constant names

### ISSUE THREAD

**Issue by wlmoss** [editorscut/ec007-swift-kickstart#119]
Book Version: 1.8
Chapter: 3 Variables and Constants
Section: 5 Numeric Types
Page number: 54

CONTEXT:
(second code block on the page)
....
`let someInt = 5`
`let someDouble = 3.4`
....

EXPLANATION:
The rest of the chapter (code and text) uses constants named **five** and **threePointFour** instead of **someInt** and **someDouble**. The fix is either to change these to be `five` and `threePointFour` or to change the usage throughout the chapter of the others to `someInt` and `someDouble`

**Comment by dimsumthinking** [comment]
Thank you -

I apologize for that mistake. I've fixed it and it will appear as part of version 1.9. Thank you for reporting it.
