### ISSUE TITLE
Missing imageView.image code Version 1.8, Chapter 3, Section 6, Page 58-59

### ISSUE THREAD

**Issue by wlmoss** [editorscut/ec007-swift-kickstart#120]
Book Version: 1.8
Chapter: 3 Variables and Constants
Section: 6 Nil
Page Number: 58 - 59

**Context:**
> Suppose you want to create and display an image. Add these two lines to our playground page.

    import UIKit
    let image = UIImage(named: "Kickstart.jpg")

**Description:**
In the two code blocks that follow, the line `imageview.image` has been omitted. Without it, the image will never display in the Quickview. (Either `nil` or the `<UIImageView: 0x7fc...>` id will show, but not the image itself). 

**Fixes:**
You could add `imageview.image` at the end of the next code block where you add the statement to create the UIImageView and the if-else statement, but...

Because the chapter is about nil, force unwrapping, and the if-let statement, it might be better to change  the original code block (above) so the reader creates all the pieces needed to start. 

> Suppose you want to create and display an image. **Start by adding this code** to our playground page.

    import UIKit
    let image = UIImage(named: "Kickstart.jpg")
    let imageView = UIImageView()
    // We will pass the image to the imageView
    imageView.view

Then, the reader can concentrate on the force unwrapping and the if-let shortcut in the next two code blocks.

**Comment by dimsumthinking** [comment]
As suggested I've added the imageView.view call in the if and if let code and called out the results

Thank you,

Daniel
