### ISSUE TITLE
Word "Material" left over at the beginning of a sentence? p. 240

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#122]
Version 1.9 P 240
Last paragraph, 3rd sentence from last.
"Material the final chapter of the last version was filled with odds and ends."

Guessing the word "material" from the next sentence stayed from the last revision ;-) 
Remove "Material"
and the sentence flows nicely.

**Comment by dimsumthinking** [comment]
Thank you - I've removed the word for version 2.0
