### ISSUE TITLE
Missing space after period of 1st sentence. 

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#125]
Version 1.9 Chapter 1 Section 4 P. 8
Missing space after period of 1st sentence. 
"... in the console.In a Swift project, ..."

NB: let me know if that is way too picky an editing. I feel overzealous but I do see the difference in spacing. (blame my new bifocals if you wish ;-)

**Comment by dimsumthinking** [comment]
I really appreciate these (and surely you're too young for bifocals).

Fixed for 2.0

**Comment by nwreg** [comment]
You are welcome and no, not too young for bifocals. I am on my second pair now :-} 

Regine Horteur-Edjlali
rhorteur@me.com
