### ISSUE TITLE
The version referred to is 1.8 on page 16, while p. 240 shows Version 1.9 to be the latest

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#126]
Version 1.9 Chapter 1 Section 8 Links 2nd paragraph, 2nd sentence.
"Please provide the book version (currently Version 1.8), ..." 
From the end of the book on p. 240, it seemed this is Version 1.9.

**Comment by dimsumthinking** [comment]
Thank you - updated to 2.0 here.
