### ISSUE TITLE
Where to find the file Kickstart.jpg: iTunes or code download? Bit unclear to me.

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#130]
Version 1.9 Chapter 3 Variables and constants Section 6 Nil p. 60
“ Download this book's cover image from iTunes and name the file Kickstart.jpg. "

from iTunes? I did find it in the code download of the playground for this chapter, that I got from the GitHub page that is referenced as a resource in the book.

**Comment by dimsumthinking** [comment]
thanks - your way is better. I've now added the jpg to the code download in a more obvious place and changed the prose.

Thank you
