### ISSUE TITLE
Should we have the parameter name in the signature of the returned function?

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#131]
Version 1.9 Chapter 3 Variables and Constants Section 7 Higher Order Functions p.62

“func createGreetingWithSalutation(salutation: String) -> (name: String) -> String ”

Here we see (name: String ) in the signature of the returned function , while the next lines of code showing its implementation do not contain it.
“func createGreetingWithSalutation(salutation: String) -> (String) -> String {”

**Comment by dimsumthinking** [comment]
I added name:. We actually don't need it but I need to be consistent. Thank you!
