### ISSUE TITLE
Ch1S4: space before comma in "...Show Debug Area , use the keyboard..."

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#133]
Ch1S4p8: 
![screen shot 2015-09-13 at 4 41 13 pm](https://cloud.githubusercontent.com/assets/1350470/9839680/47f856d8-5a36-11e5-95f8-32cbd80cdc08.png)

**Comment by dimsumthinking** [comment]
fixed in V 2.0 - thank you
