### ISSUE TITLE
'Click' vs 'tap'

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#134]
Many sections of text refer to clicking on UI elements on a Mac, which is pretty standard. Other sections (e.g. Ch1S5p11 demonstrating the Quick Look and inline result views) refer to tapping, which is generally reserved for interacting with a user interface directly with a finger,

**Comment by dimsumthinking** [comment]
Thank you - I've changed the taps to clicks

fixed in version 2.0
