### ISSUE TITLE
Two periods at end of sentence

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#135]
Ch1S5p11
Not sure if you want a period or ellipses, but two dots isn't either. 
![screen shot 2015-09-13 at 4 48 44 pm](https://cloud.githubusercontent.com/assets/1350470/9839746/5fc1ee4a-5a37-11e5-999a-844cc85254b0.png)

**Comment by dimsumthinking** [comment]
Thank you - that was meant to be a period - thank you

fixed in 2.0
