### ISSUE TITLE
2.1 A ')' got wrong color coding

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#136]
Ch2S1p21 Note the ')' on line 3 is blue while the rest of the line is red. 

![screen shot 2015-09-13 at 4 56 18 pm](https://cloud.githubusercontent.com/assets/1350470/9839800/79ee4fe2-5a38-11e5-8a91-319b70c3e4b4.png)

**Comment by dimsumthinking** [comment]
Thank you - fixed for V 2.0
