### ISSUE TITLE
2.7 subject-verb agreement

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#137]
Either "We can create ^a^ function" 
Or "We can create functions"

![screen shot 2015-09-13 at 5 04 39 pm](https://cloud.githubusercontent.com/assets/1350470/9839850/a49615ee-5a39-11e5-8e88-fa1416ed5e0d.png)

**Comment by dimsumthinking** [comment]
Thank you - decided on plural.

Fixed in V 2.0
