### ISSUE TITLE
2.10: missing period at end of sentence

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#139]
Ch2S10p43
I think there should be a period after the very last word.

![screen shot 2015-09-13 at 5 34 43 pm](https://cloud.githubusercontent.com/assets/1350470/9839966/cbe7eab0-5a3d-11e5-9337-0cbbc2b60ca0.png)

**Comment by dimsumthinking** [comment]
Thank you - I've fixed this for version 2.0
