### ISSUE TITLE
4.1 "Dictionarys" should be "Dictionaries"

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#140]
Ch4S1p74
![screen shot 2015-09-13 at 5 50 01 pm](https://cloud.githubusercontent.com/assets/1350470/9840055/edecac16-5a3f-11e5-8b39-f344f266894f.png)

**Comment by dimsumthinking** [comment]
I was stumped by this. I set Array and Dictionary in code font because they are actual types. I've now changed them to the more generic - but more easily read - arrays and dictionaries as you suggest. 

Thank you
