### ISSUE TITLE
4.10 'is' should be 'if' ?

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#141]
I think you mean 'if' instead of 'is'. 

![screen shot 2015-09-13 at 6 10 50 pm](https://cloud.githubusercontent.com/assets/1350470/9840182/d421606c-5a42-11e5-94cc-0abffd6c6ee1.png)

**Comment by dimsumthinking** [comment]
Thank you - this is fixed for version 2.0
