### ISSUE TITLE
6.2 Output scrambled in enumeration -> UIColor example

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#143]
Ch6S2p134
The output you provided in the sample code has a red dot for the Green output, a green dot for the Red output, and the same RGBA value for both (which is incorrect for red).
![screen shot 2015-09-13 at 10 40 58 pm](https://cloud.githubusercontent.com/assets/1350470/9842858/ce8ed67c-5a68-11e5-9a2a-b22b0f01a6e0.png)

In Xcode 7GM, the colors are represented correctly in both dot preview and RGBA form: 

![screen shot 2015-09-13 at 10 41 48 pm](https://cloud.githubusercontent.com/assets/1350470/9842876/16811170-5a69-11e5-8fe3-722eb8b8e34a.png)

BONUS ACCESSIBILITY CONSIDERATION:
Since a non-trivial portion of the population is red/green colorblind, and you've already set up the blue enumeration as well, consider using blue as one of the two colors here.

**Comment by dimsumthinking** [comment]
Ok - changed to Green and Blue for the full win!

Thank you for the error spotting and the accessibility note.
