### ISSUE TITLE
6.10 '??' described as already seen, but maybe wasn't

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#145]
When my sweetie read through the book, he got to this sentence and asked me what '??' did. It's tough to search for '??' in iBooks, so I don't feel sure, but I think this might not have been covered earlier. 
![screen shot 2015-09-13 at 10 57 14 pm](https://cloud.githubusercontent.com/assets/1350470/9843015/fde414da-5a6a-11e5-9dab-71dc62eda8c6.png)

'guard let' also felt unfamiliar to me, but I found its introduction on p95. It feels a bit tucked in there. Perhaps it warrants a little more discussion?

Since these are kind of complex, similar concepts that were discussed many pages earlier, is it possible to make them links back to their respective sections? Especially '??' since it's fairly unsearchable?

**Comment by dimsumthinking** [comment]
Thanks - I try to use the term nil coalescing operator when I use ?? as coalescing is searchable. BUT - I reorganized the book and don't explain it until after this point. Thank you for catching this and I apologize to both of you for this.

I'm rephrasing this paragraph.

Unfortunately iBooks doesn't let me easily link between files (nor does it let me create an index which is what I'd really love as we could use synonyms for these terms and people could find them using whichever version they like - yes I've filed that radar)

Thank you again for your thoughtful comments on this book.
