### ISSUE TITLE
4.8 "let's" should be replaced with "lets"

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#146]
Ch4S8p95
lets = allows
let's = let us
In this case, 'allows' is the sense I think you want. 

![screen shot 2015-09-13 at 11 03 04 pm](https://cloud.githubusercontent.com/assets/1350470/9843111/0cdc9fa6-5a6c-11e5-86b4-441a51e52751.png)

**Comment by dimsumthinking** [comment]
Thank you - that's embarrassing. I appreciate you finding it and reporting it
