### ISSUE TITLE
3.5 "Remember" a concept that hasn't yet been discussed

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#148]
I agree with this sentiment, but could not find a place earlier in the book where you expressed it. Perhaps it should be expounded on earlier, or perhaps you could rework this to be the main place you discuss it. (Or perhaps I just skimmed too quickly, and it was discussed earlier!)

<img width="808" alt="screen shot 2015-09-14 at 8 32 25 pm" src="https://cloud.githubusercontent.com/assets/1350470/9867203/d59f55a6-5b1f-11e5-8c28-aa21eb667e24.png">

**Comment by dimsumthinking** [comment]
Thank you - I think I removed the antecedent. Thank you for pointing this out.

Rephrased in 2.0
