### ISSUE TITLE
7.9 "Protocol oriented Programming" formatting

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#149]
Ch7S9p180
You refer to the paradigm without a hyphen and with mixed capitalization.
<img width="821" alt="screen shot 2015-09-14 at 8 47 24 pm" src="https://cloud.githubusercontent.com/assets/1350470/9867396/fb7131c6-5b21-11e5-9d5c-bf28f7644e35.png">

Apple seems to prefer a hyphen and either all caps (as in the video title) or all lower case. 
https://developer.apple.com/videos/wwdc/2015/?id=408
<img width="822" alt="screen shot 2015-09-14 at 8 47 53 pm" src="https://cloud.githubusercontent.com/assets/1350470/9867397/fe188b9a-5b21-11e5-9b13-5b6397639d0d.png">

**Comment by dimsumthinking** [comment]
Thank you. I've adjusted this as you suggest to match Object-Oriented earlier in the text.

Thanks
