### ISSUE TITLE
8.8 space before a comma

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#150]
Ch8S8p198 
There's a stray space between "or" and the comma that follows.

<img width="820" alt="screen shot 2015-09-14 at 9 00 32 pm" src="https://cloud.githubusercontent.com/assets/1350470/9867534/bf2bf2da-5b23-11e5-9c2b-dd9393f3f32b.png">

**Comment by dimsumthinking** [comment]
fixed, thank you
