### ISSUE TITLE
8,8 Missing playground responses in some code listings?

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#151]
I'm not sure about this...since I'm only reading through the book this time, not typing along, I may be overlooking a distinction. 

In lots of places, there's playground responses along the right side as comments. For example, in 8.8:
<img width="836" alt="screen shot 2015-09-14 at 9 05 13 pm" src="https://cloud.githubusercontent.com/assets/1350470/9867594/55bd720a-5b24-11e5-8e94-09d70c27172e.png">

And that seems helpful. 

But sometimes there isn't, and it's not entirely clear to me why not. For example, here's a case (also from 8.8) where the response is omitted, even though the sentence before explicitly refers to it. 
<img width="714" alt="screen shot 2015-09-14 at 9 03 32 pm" src="https://cloud.githubusercontent.com/assets/1350470/9867597/6aac8d9a-5b24-11e5-97ce-19963008c699.png">

If you do decide to fill in responses, please be aware this isn't the only place I've felt the response was missing.

**Comment by dimsumthinking** [comment]
Thanks - in general I've left out playground feedback when it hasn't changed or isn't important. Clearly, you've found a place here where I'm calling it out so it should be included. 

This will be the last issue I address before posting the book as I think it needs a quick sweep of the entire book to address it.

Thanks again - leaving this open til I address it.

**Comment by dimsumthinking** [comment]
Thank you - fixed in 2.0
