### ISSUE TITLE
9.8 grammar nitpick: parallel clauses

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#153]
Ch9S8p224
The clauses about daniel and kimberli are nearly parallel, but 'has' is a verb, creating a thing that could be a complete sentence, while 'with' creates a sentence fragment. This feels unbalanced to me. Maybe switch one of them so they use the same joining word?

<img width="831" alt="screen shot 2015-09-14 at 9 25 58 pm" src="https://cloud.githubusercontent.com/assets/1350470/9867893/4d16380a-5b27-11e5-8562-5aaa4d0e318e.png">

**Comment by dimsumthinking** [comment]
Your way is much better - thank you
