### ISSUE TITLE
9.8 formatting of 'nil'

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#154]
Ch9S8p227
In this paragraph you go back and forth between styling 'nil' as code and leaving it as plain text. You might have been very strategic here. But I'm a little sleepy and it feels a little haphazard jumping back and forth. 

<img width="837" alt="screen shot 2015-09-14 at 9 33 49 pm" src="https://cloud.githubusercontent.com/assets/1350470/9868001/7fb7d6e6-5b28-11e5-82f2-021e64026991.png">

**Comment by dimsumthinking** [comment]
Thank you - totally an error on my part. Fixed.
