### ISSUE TITLE
9.11 Missing 'and' in list of Swift structs

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#156]
Ch9S11p234
This list of structs has 'and' before the final one: 
<img width="826" alt="screen shot 2015-09-14 at 9 38 53 pm" src="https://cloud.githubusercontent.com/assets/1350470/9868060/34f6887c-5b29-11e5-87bb-8993adc6d9d1.png">

This one does not:
<img width="802" alt="screen shot 2015-09-14 at 9 39 10 pm" src="https://cloud.githubusercontent.com/assets/1350470/9868063/3c7833a2-5b29-11e5-9642-ec83e1b58a8f.png">

**Comment by dimsumthinking** [comment]
Fixed, thank you
