### ISSUE TITLE
10.0 Mailing list link is missing

### ISSUE THREAD

**Issue by emarley** [editorscut/ec007-swift-kickstart#157]
Ch10[intro]p236
The text promises a link to subscribe to the mailing list, but there isn't one. (And this made me sad on top of being an error, because I actually want to subscribe!)
<img width="543" alt="screen shot 2015-09-14 at 9 42 19 pm" src="https://cloud.githubusercontent.com/assets/1350470/9868090/937ce3dc-5b29-11e5-8677-800c1d9017d6.png">

**Comment by dimsumthinking** [comment]
Thank you - fixed
