### ISSUE TITLE
4.1 Difference of font on "it is [NSObject] "

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#159]
Version 1.9 Chapter 4 Collections. Section 1. One Type. p. 73
“Option-click on badNumbers and you'll see that it is [NSObject].”
Copy and paste here doesn't reflect the way "it is [NSObject]" is appearing in iBooks. 
There, it shows as a script type of font (sorry, don't have the right name for it) instead of like the font of the rest of the sentence. 
Did you want to have "badNumbers" and [NSObject] showing up the same way?

**Comment by dimsumthinking** [comment]
thanks - the problem was I had "It is" also set in code font - fixed thank you
