### ISSUE TITLE
4.1 Question/suggestions about the bubbles' conversation device

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#160]
Version 1.9 Chapter 4 Collections Section 1 One Type.p 71-72
This is totally suggestive on my part: p. 71 and 72, you have those conversation bubbles going on to show what Objective-C programmers (for example) would say to you when you tell them of the constraint of homogeneity in Swift arrays. 
I know that in your very early versions last summer, you had things like that or those side notes. 
I have not finished reading this version but skimming rapidly, I did not seem to find other occasions you used this device, so it feels a little out of place there in my taste, especially since you have no problem writing as if in a conversation with the reader. (which is one of your trademark writing style in my view, and I appreciate it very much)
I know it is a big deal of a difference between Objective-C and Swift, but I am sure you can convey that point in the text with a few sentences.

**Comment by dimsumthinking** [comment]
I will come back to this later. You're not wrong - i'm just not emotionally ready to remove these. 

You're right - slowly I've removed all of the bubbles except these. These need to go and they will go in 2.0. But not til I've had more coffee

Thanks.

**Comment by dimsumthinking** [comment]
Oops that was supposed to be a comment without closing - I haven't resolved it yet.

**Comment by dimsumthinking** [comment]
OK - removed the balloons. Thank you.

**Comment by nwreg** [comment]
:-) More coffee seems only appropriate! Same here. 


Regine Horteur-Edjlali
rhorteur@me.com
