### ISSUE TITLE
 Ch 1 - Sec 8The two Apple Swift books on iBooks show as not available in US (as of today Sept 21, 2015)

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#161]
Version 2.0 Chapter 1. Section 8 Links p. 16

Text of the alert in case the screenshot did not go through.

"Item Not Available
The item you've requested is not currently available in the U.S. store."

![screen shot 2015-09-21 at 11 41 14 am](https://cloud.githubusercontent.com/assets/8108318/10001289/df5539fe-6055-11e5-8aea-a21cd2126833.png)

**Comment by dimsumthinking** [comment]
Thank you - Apple changed the id numbers - I've made the corresponding change. Thank you for spotting this.
