### ISSUE TITLE
Ch 4 Sec 8 Two typos in “It's type is Int?.. "

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#164]
Version 2.0 Chapter 4 Section 8 Optionals and Dictionaries p. 94 mid page.
“It's type is Int?.. ”
Just one period after the optional notation there should be enough.

**Comment by nwreg** [comment]
And "It's type" should be "Its type".
Saved the issue too fast ;-)

**Comment by dimsumthinking** [comment]
Thank you - fixed both
