### ISSUE TITLE
2.3 Results View 'toggle button' no longer appears to exist for Strings 

### ISSUE THREAD

**Issue by Diggory** [editorscut/ec007-swift-kickstart#166]
In section 2.3 'Overloading' (Book v2.0) on page 26

There are a couple of screenshots and some text which describe the toggle button in the Results View that allows toggling of 'current value' or 'all values'.

Xcode appears to have removed that toggle switch in version 7.0 (at least for String results) in favour of a contextual menu.

![screen-shot-2015-09-27-at-11 49 12](https://cloud.githubusercontent.com/assets/743811/10122355/7b8ea99c-650e-11e5-83c8-70598d50f2a0.png)

**Comment by dimsumthinking** [comment]
Thank you - this did change - I've reshot the screenshots and adjusted the description. Thank you.
