### ISSUE TITLE
2.11 English usage: "In so many of the languages" 

### ISSUE THREAD

**Issue by Diggory** [editorscut/ec007-swift-kickstart#167]
In section 2.11 (So.. section of Functions Chapter) - page 44 (Book Version 2.0)

The text reads:

"Swift's syntax for return types also takes some getting used to.  In so many of the languages, the return type is at the left before the function or method name."

That reads a little oddly to me - surely it should be "In so many languages" or "In so many other languages" or "In so many of the languages that have preceded Swift".

Just a style thing I suppose.  The 'the' just jars for me.

Really enjoying the book!

**Comment by dimsumthinking** [comment]
Thank you - sorry about that. Fixed.
