### ISSUE TITLE
3.6 Playgrounds no longer render UIImageViews 

### ISSUE THREAD

**Issue by Diggory** [editorscut/ec007-swift-kickstart#168]
Chapter 3 section 6 (book v2.0 page 60) 'Nil'

The text reads: 
> "This time the playground feedback is w 172 h 225" which are the dimensions of the imageView.  Click the Show Result Icon to see the image of the book cover.

It appears that in Xcode 7.0 UIImageViews are no longer rendered in the playgrounds.  On my machine the result is rendered as the description of the UIImageView:  (UIImages do appear to render though)

    <UIImageView: 0x7fb255300260; frame = (0 0; 0 0); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x7fb255301780>>

![uiimage](https://cloud.githubusercontent.com/assets/743811/10122849/0cfe5318-651f-11e5-8af0-f01e29fcd832.png)

**Comment by dimsumthinking** [comment]
Sorry -  You are correct. The problem is that my writing is sloppy here. I meant this to refer to the line imageView.image but see how it seems to refer to imageView. I've rewritten this paragraph.

Thank you - and sorry for the confusion.

Daniel
