### ISSUE TITLE
Ch 5 ? Sec 9 No hint of trying that code in the playground

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#173]
Version 2.0 Section 9 Transforming Arrays P. 124-125
This time around (unlike all the preceding chapters and sections), there is no mentioning of opening a new playground page and trying out that code. Omission?

**Comment by nwreg** [comment]
Actually, same thing in Section 10. 
Maybe I missed a part earlier that explicitly said to try it out. 
I know the reader can figure it out. I was just noticing for consistency's sake. (aka... me being mean and picky on some stuff sometimes ;-)

**Comment by dimsumthinking** [comment]
fixed - thank you
