### ISSUE TITLE
Ch 6 Sec 1 A bit of a color name mix up between the code shown and the text on p. 131

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#175]
Version 2.0 Chapter 6 Enumerations Section 1 Creating an enumeration. p.131

The paragraphs of text suggest some colors for examples but it is not represented in the code shown, like "Choose Green" and the code has Color.Red 
Same for changing the color value of crayon to Blue, and the code shows is Green. 
Same for the paintbrush example: mismatch of color.

**Comment by dimsumthinking** [comment]
Thank you - fixed
