### ISSUE TITLE
Ch 6 Sec 5 Maybe suggests doing an Option-click to discover the type of paintBrush

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#177]
Version 2.0 Chapter 6 Section 5 String Raw Values p. 141
“Note, paintBrush has type Color? because ...”

You might want to point out to do an Option Click on paintBrush to discover its type, a Color?
Or you might think the reader knows the trick by now ;-) 
It is just that you used to say so earlier in the book.

**Comment by dimsumthinking** [comment]
Thank you - fixed
