### ISSUE TITLE
Ch 6 Sec 5 Might be confusing for the default enumerations part

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#178]
Version 2.0 Chapter 6 Section 5 String Raw Values p. 140

There might be some confusion between those 2 parts on p. 140

“In Swift, by default enumerations have no underlying values but”
and 
“If we don't specify the String value for each enumeration value, they automatically have the String equivalent of their name. ”

**Comment by dimsumthinking** [comment]
Thank you - I've rewritten the opening paragraphs to (I hope) address this.
