### ISSUE TITLE
Ch 6 Sec 10 "The console output: " part does not appear in the playground

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#180]
Version 2.0 Chapter 6 Section 10 Error Type p. 154

"// The console output: double 8 = 16" actually shows only as "double 8 = 16"
Same for the next line of code. 
You did explain that it would be the console output in the line just before that "screenshot" of the cautiousDoubler() calls.

**Comment by dimsumthinking** [comment]
I've changed the prose and the font - thank you.
