### ISSUE TITLE
Ch 7 Sec 4 Unsure of reason to have that code testing x for equality to 8

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#182]
Version 2.0 Chapter 7 Struct Section 4 Will Set and Did Set p. 170.

I am sure of the reason to have that bit of code testing for x being equal to 8 and if yes, getting it to be -8 instead. Maybe a remnant of earlier code? (I can't remember from the older versions)

 didSet {
        print("The value of x has changed from \(oldValue) to \(x).")
        if x == 8.0 {
            x = -8.0
        }
    }

**Comment by dimsumthinking** [comment]
Sorry - I left out a lot of information - I'm demonstrating how to perform validation inside of didSet().

Thank you for the issue - fixed.
