### ISSUE TITLE
Ch 9 Sec 4 The hometown shown for Daniel is Shaker Heights, and for Kimberli too in the code for extension.

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#186]
Version 2.0 Chapter 9 Classes Section 4 Methods. P. 215

From the code below the extension on the top of the page, we would expect the default value for both hometowns, Cupertino.

**Comment by dimsumthinking** [comment]
Sigh - sorry about that. Thank you for catching this.
