### ISSUE TITLE
Ch 9 Sec 5 Extra period after nil in the middle of last sentence.

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#187]
Version 2.0 Chapter 9. Section 5 Optional Property Value p. 217

“ As a ConferenceAttendee, daniel's hometown is nil. and as a TutorialAttendee, kimberli's hometown is "Cupertino"."
There is an extra period right after nil.

**Comment by dimsumthinking** [comment]
Thank you, fixed.
