### ISSUE TITLE
Ch 9 Sec 5 We are changing the code in the init of class TutorialAttendee, not in its nameBadge code

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#188]
Version 2.0 Chapter 9 Section 5 Optional Property Value p. 218

“Change nameBadge() in TutorialAttendee so that hometown's type is String? and default value is nil.
”
We actually modify the init method, not the nameBadge method.

**Comment by dimsumthinking** [comment]
Thank you, fixed.
