### ISSUE TITLE
Ch 9 Sec 9 "when an ConferenceAttendee" to be replaced by "when a ConferenceAttendee"

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec007-swift-kickstart#190]
Version 2.0 Chapter 9. Section 9 p. 230

The article preceding ConferenceAttendee should be "a", not "an".
“We clear out resources when an ConferenceAttendee instance is about to go away with a deinit clause.”

**Comment by dimsumthinking** [comment]
Thank you, fixed
