### ISSUE TITLE
Chapter 4, section 4 (page 78) - code is incorrect (and doesn't match repo)

### ISSUE THREAD

**Issue by mtancock** [editorscut/ec007-swift-kickstart#83]
I have version 1.6. I'm hoping that's the latest version!!
(Edited to add: Love the book by the way - thanks for writing it!)

Code at top of page 78 reads:

```swift
for var index = 0; index < coffeeDrinks.count; index++ {
    results += coffeeDrink[index] + "\n"
}
```

According to the repo here (and the partially obscured screenshot in the book shows that it's not quite the same) it should be:

```swift
for  var index = 0; index  < coffeeDrinks.count; index++  {
    results += item(number: index + 1) + coffeeDrinks[index]
}
```

**Comment by dimsumthinking** [comment]
Thank you - 

You're correct. This is now fixed in Version 1.7 - Thanks for the kind words.

Thanks,

Daniel
