### ISSUE TITLE
Chapter 5, section 8, Mutating functions (page 115) refers to function sorting() instead of sorted()

### ISSUE THREAD

**Issue by mtancock** [editorscut/ec007-swift-kickstart#84]
version 1.6
Chapter 5, section 8
Page 115
The code is all correct, but after the first paragraph and code sample on page 115, all of the other text refers to the function sorting() rather than sorted()

**Comment by dimsumthinking** [comment]
Thank you,

I've fixed this for version 1.7

Best,

Daniel
