### ISSUE TITLE
Section 10/11 of Chapter 6

### ISSUE THREAD

**Issue by mtancock** [editorscut/ec007-swift-kickstart#85]
Version 1.6
Section 10 starts by asking us to create a new playground with some code.

Section 11 starts by saying "Before we adjust our playground... and then goes on to talk about the playground state as it was at the end of section 9. 

For organised people who have all of the playgrounds saved, once you work out that's what it's referring to, that's fine. But seems like something has changed along the line and the order has got thrown out which is slightly confusing until you realise!

**Comment by dimsumthinking** [comment]
Thank you - I've added prose to Sections 10 and 11 to make this more clear.

This is fixed in Version 1.7

Thank you,

Daniel
