### ISSUE TITLE
Chapter 6.3...

### ISSUE THREAD

**Issue by mdeh** [editorscut/ec007-swift-kickstart#86]
ballHanlder.rawValue   Error: BasketballPosition does not have a member named 'rawValue'

Changing rawValue to .toRaw() eliminates the error and gives the correct value.

**Comment by dimsumthinking** [comment]
Reopening as I'm doing an errata sweep and need to ensure I've taken care of this

**Comment by dimsumthinking** [comment]
Thanks again - this is fixed in Version 1.7
