### ISSUE TITLE
Minor typo in Functions Chapter, Page 28

### ISSUE THREAD

**Issue by sansari** [editorscut/ec007-swift-kickstart#87]
Book Version: 1.6
Chapter: 2 - Functions
Section: 5 - Default Values
Page number: 28

After the second code sample, when it asks "Which version of helloWorld() is called when we call helloWorld("Swift Developer")?" -- it should be asking "when we call helloWorld("Swift Programmer")

**Comment by dimsumthinking** [comment]
Reopening as I'm doing an errata sweep and need to ensure I've taken care of this

**Comment by dimsumthinking** [comment]
Fixed for real this time! Thank you.

Daniel
