### ISSUE TITLE
Minor typo in Functions, Page 31

### ISSUE THREAD

**Issue by sansari** [editorscut/ec007-swift-kickstart#88]
Book Version: 1.6
Chapter: 2 - Functions
Section: 6 - External Names
Page number: 31

After the creation of hello2() func, it says "there's an error in our current call of hello2() until we add the parameter name back in like this". At that point, there was no call to hello2 -- the instructions only asked to create the hello2 func, not the call.

**Comment by dimsumthinking** [comment]
Fixed, thank you
