### ISSUE TITLE
Functions, Page 32

### ISSUE THREAD

**Issue by sansari** [editorscut/ec007-swift-kickstart#89]
Book Version: 1.6
Chapter: 2 - Functions
Section: 6 - External Names
Page number: 32

After the second code sample, when it asks "Which version of helloWorld() is called when we call helloWorld("Swift Developer")?" -- it should be asking "when we call helloWorld("Swift Programmer")

The last paragraph says "For example, let's provide an external name for the *required* parameter in hello2()".

Shouldn't it say for the *optional* parameter, since it takes a default value?

**Comment by dimsumthinking** [comment]
Reopening as I'm doing an errata sweep and need to ensure I've taken care of this

**Comment by dimsumthinking** [comment]
Fixed as you asked - thank you.
