### ISSUE TITLE
Functions, Page 40

### ISSUE THREAD

**Issue by sansari** [editorscut/ec007-swift-kickstart#90]
Book Version: 1.6
Chapter: 2 - Functions
Section: 7 - Returning Tuples
Page number: 40

Second example asking you to append .1 to function call does not actually do so in the code sample (even though output on right is changed)

**Comment by dimsumthinking** [comment]
Thanks both -

I fixed the first typo you referred to.

As to your second point, as Brian pointed out, the book code does not include the \n in the reduce that I have included in the sample code. I've revised the code in the book accordingly.

Thank you both - this is now fixed.

Daniel
