### ISSUE TITLE
Variables, Page 57

### ISSUE THREAD

**Issue by sansari** [editorscut/ec007-swift-kickstart#91]
Book version: 1.6
Chapter: Variables
Page: 57

When you mention the "don't do this" bit at the top:

```swift
let simpleHello:(String) -> String = sayHello // don't do this
```

it should really be:

```swift
let simpleHello:(toPersonWithName: String) -> String = sayHello // don't do this
```

in order to match the sayHello definition that provides an external name. it suggests not doing it just for the sake of inference, but in this case calling simpleHello(toPersonWithName: "there") would not work without it.

**Comment by dimsumthinking** [comment]
As you say, if we don't include the toPersonWithName: there we lose the external name for the variable 

Thank you - this is fixed in Version 1.7.
