### ISSUE TITLE
Collections, Page 74

### ISSUE THREAD

**Issue by sansari** [editorscut/ec007-swift-kickstart#92]
Book: v1.6
Chapter: 4 - Collections
Section: 3
Page: 74

When discussing the error accessing index 7, a few things are different in my experience. Firstly, "Mocha" does not show up on the right. Secondly, the error is different: http://note.io/1xQmV0n

Lastly, I think there is a typo in the line which says "there is no feedback for coffeeDrink.numbers" -- I think that's meant to be coffeeDrink.count

**Comment by dimsumthinking** [comment]
Thank you both again - this is fixed in Version 1.7.

Thanks,

Daniel
